
// カテゴリー情報（小学生が直感で選べるテーマ）
export const KANJI_CATEGORIES = [
  {
    id: 'nature',
    name: '自然と天気',
    emoji: '🌿',
    description: '海や雨、雲など自然の漢字',
    gradient: 'linear-gradient(135deg, #60a5fa, #06b6d4)',
  },
  {
    id: 'school',
    name: '学校と勉強',
    emoji: '🏫',
    description: '学校で使うことばの漢字',
    gradient: 'linear-gradient(135deg, #fbbf24, #f97316)',
  },
  {
    id: 'family',
    name: '家族と人',
    emoji: '👨‍👩‍👧‍👦',
    description: 'お父さん、お母さん、お友達',
    gradient: 'linear-gradient(135deg, #f472b6, #f43f5e)',
  },
  {
    id: 'time',
    name: '時間と日にち',
    emoji: '🕒',
    description: '時間や曜日の漢字',
    gradient: 'linear-gradient(135deg, #c084fc, #6366f1)',
  },
  {
    id: 'animals',
    name: '動物・植物・食べ物',
    emoji: '🐶',
    description: 'いきものや食べ物の漢字',
    gradient: 'linear-gradient(135deg, #34d399, #16a34a)',
  },
  {
    id: 'places',
    name: '街・場所・方角',
    emoji: '🏙️',
    description: 'お店や東西南北など',
    gradient: 'linear-gradient(135deg, #38bdf8, #2563eb)',
  },
  {
    id: 'actions',
    name: 'うごきとことば',
    emoji: '🔢',
    description: '行く、話す、聞くなど',
    gradient: 'linear-gradient(135deg, #a78bfa, #c026d3)',
  },
];

// 小学2年生の漢字全160字の包括的学習データベース
export const KANJI_DATA = [
  // === 自然と天気 ===
  {
    id: 'umi',
    character: '海',
    category: 'nature',
    grade: 2,
    strokeCount: 9,
    readings: {
      onyomi: ['カイ'],
      kunyomi: ['うみ'],
    },
    meaning: 'ひろい うみ',
    examples: [
      { word: '海（うみ）', reading: 'うみ', sentence: '夏休みに 海で およぐ。' },
      { word: '日本海（にほんかい）', reading: 'にほんかい', sentence: '日本海で とれた 魚。' },
    ],
    strokes: [
      {
        strokeNumber: 1,
        type: 'dot',
        start: { x: 20, y: 18 },
        end: { x: 26, y: 25 },
        svgPath: 'M 20 18 C 22 20, 24 22, 26 25',
        hintText: 'さんずい１：てんをうつ',
      },
      {
        strokeNumber: 2,
        type: 'dot',
        start: { x: 15, y: 40 },
        end: { x: 22, y: 46 },
        svgPath: 'M 15 40 C 17 42, 19 44, 22 46',
        hintText: 'さんずい２：てもうひとつ',
      },
      {
        strokeNumber: 3,
        type: 'right-sweep',
        start: { x: 14, y: 78 },
        end: { x: 26, y: 62 },
        svgPath: 'M 14 78 C 18 72, 22 66, 26 62',
        hintText: 'さんずい３：したからうえへ はねる',
      },
      {
        strokeNumber: 4,
        type: 'left-sweep',
        start: { x: 55, y: 15 },
        end: { x: 42, y: 28 },
        svgPath: 'M 55 15 C 50 20, 46 24, 42 28',
        hintText: 'みぎのうえ：ひだりへ はらう',
      },
      {
        strokeNumber: 5,
        type: 'horizontal',
        start: { x: 48, y: 28 },
        end: { x: 86, y: 28 },
        svgPath: 'M 48 28 L 86 28',
        hintText: 'よこへ まっすぐ',
      },
      {
        strokeNumber: 6,
        type: 'hook',
        start: { x: 45, y: 33 },
        end: { x: 84, y: 84 },
        svgPath: 'M 45 33 C 42 45, 38 55, 38 65 C 46 69, 65 76, 84 84',
        hintText: 'したへ おりて、みぎしたへ ながく はらう',
      },
      {
        strokeNumber: 7,
        type: 'hook',
        start: { x: 47, y: 34 },
        end: { x: 61, y: 84 },
        svgPath: 'M 47 34 L 78 36 L 74 60 L 61 84',
        hintText: 'よこから みぎしたへ まがりながら おりる',
      },
      {
        strokeNumber: 8,
        type: 'vertical',
        start: { x: 59, y: 36 },
        end: { x: 53, y: 71 },
        svgPath: 'M 59 36 L 53 71',
        hintText: 'なかの たてせん',
      },
      {
        strokeNumber: 9,
        type: 'horizontal',
        start: { x: 28, y: 54 },
        end: { x: 90, y: 51 },
        svgPath: 'M 28 54 L 90 51',
        hintText: 'ながい よこせん',
      },
    ],
  },
  {
    id: 'ame',
    character: '雨',
    category: 'nature',
    grade: 2,
    strokeCount: 8,
    readings: {
      onyomi: ['ウ'],
      kunyomi: ['あめ', 'あま'],
    },
    meaning: 'あまぐも から ふる あめ',
    examples: [
      { word: '雨（あめ）', reading: 'あめ', sentence: '今日は 朝から 雨が ふっている。' },
      { word: '大雨（おおあめ）', reading: 'おおあめ', sentence: '大雨に きを つける。' },
    ],
    strokes: [
      {
        strokeNumber: 1,
        type: 'horizontal',
        start: { x: 24, y: 18 },
        end: { x: 76, y: 18 },
        svgPath: 'M 24 18 L 76 18',
        hintText: 'よこへ まっすぐ',
      },
      {
        strokeNumber: 2,
        type: 'vertical',
        start: { x: 18, y: 32 },
        end: { x: 18, y: 88 },
        svgPath: 'M 18 32 L 18 88',
        hintText: 'ひだりのたてせん',
      },
      {
        strokeNumber: 3,
        type: 'hook',
        start: { x: 20, y: 34 },
        end: { x: 82, y: 88 },
        svgPath: 'M 20 34 L 82 34 L 82 88 L 74 88',
        hintText: 'よこへいって したへまがる',
      },
      {
        strokeNumber: 4,
        type: 'vertical',
        start: { x: 50, y: 22 },
        end: { x: 50, y: 85 },
        svgPath: 'M 50 22 L 50 85',
        hintText: 'まんなかの たてせん',
      },
      {
        strokeNumber: 5,
        type: 'dot',
        start: { x: 30, y: 48 },
        end: { x: 38, y: 56 },
        svgPath: 'M 30 48 L 38 56',
        hintText: 'ひだりうえの てん',
      },
      {
        strokeNumber: 6,
        type: 'dot',
        start: { x: 28, y: 70 },
        end: { x: 36, y: 78 },
        svgPath: 'M 28 70 L 36 78',
        hintText: 'ひだましたの てん',
      },
      {
        strokeNumber: 7,
        type: 'dot',
        start: { x: 62, y: 48 },
        end: { x: 70, y: 56 },
        svgPath: 'M 62 48 L 70 56',
        hintText: 'みぎうえの てん',
      },
      {
        strokeNumber: 8,
        type: 'dot',
        start: { x: 62, y: 70 },
        end: { x: 70, y: 78 },
        svgPath: 'M 62 70 L 70 78',
        hintText: 'みぎしたの てん',
      },
    ],
  },
  {
    id: 'kumo',
    character: '雲',
    category: 'nature',
    grade: 2,
    strokeCount: 12,
    readings: {
      onyomi: ['ウン'],
      kunyomi: ['くも'],
    },
    meaning: 'そらに うかぶ くも',
    examples: [
      { word: '雲（くも）', reading: 'くも', sentence: '白い 雲が そらに うかぶ。' },
      { word: '雨雲（あまぐも）', reading: 'あまぐも', sentence: '黒い 雨雲が 近づく。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 28, y: 14 }, end: { x: 72, y: 14 }, svgPath: 'M 28 14 L 72 14', hintText: 'よこへ まっすぐ' },
      { strokeNumber: 2, type: 'vertical', start: { x: 20, y: 24 }, end: { x: 20, y: 44 }, svgPath: 'M 20 24 L 20 44', hintText: 'ひだりのたてせん' },
      { strokeNumber: 3, type: 'hook', start: { x: 22, y: 26 }, end: { x: 80, y: 44 }, svgPath: 'M 22 26 L 80 26 L 80 44 L 74 44', hintText: 'よこへいって したへまがる' },
      { strokeNumber: 4, type: 'vertical', start: { x: 50, y: 16 }, end: { x: 50, y: 42 }, svgPath: 'M 50 16 L 50 42', hintText: 'まんなかの たてせん' },
      { strokeNumber: 5, type: 'dot', start: { x: 30, y: 32 }, end: { x: 38, y: 38 }, svgPath: 'M 30 32 L 38 38', hintText: 'あめかんむり：ひだり うえの てん' },
      { strokeNumber: 6, type: 'dot', start: { x: 30, y: 40 }, end: { x: 38, y: 46 }, svgPath: 'M 30 40 L 38 46', hintText: 'あめかんむり：ひだり したの てん' },
      { strokeNumber: 7, type: 'dot', start: { x: 62, y: 32 }, end: { x: 70, y: 38 }, svgPath: 'M 62 32 L 70 38', hintText: 'あめかんむり：みぎ うえの てん' },
      { strokeNumber: 8, type: 'dot', start: { x: 62, y: 40 }, end: { x: 70, y: 46 }, svgPath: 'M 62 40 L 70 46', hintText: 'あめかんむり：みぎ したの てん' },
      { strokeNumber: 9, type: 'horizontal', start: { x: 26, y: 56 }, end: { x: 74, y: 56 }, svgPath: 'M 26 56 L 74 56', hintText: 'したの よこせん１' },
      { strokeNumber: 10, type: 'horizontal', start: { x: 18, y: 70 }, end: { x: 82, y: 70 }, svgPath: 'M 18 70 L 82 70', hintText: 'ながい よこせん' },
      { strokeNumber: 11, type: 'curve', start: { x: 47, y: 67 }, end: { x: 67, y: 80 }, svgPath: 'M 47 67 C 40 76, 33 82, 32 84 C 40 87, 55 85, 67 80', hintText: 'したへ さがって、みぎへ まきかえす' },
      { strokeNumber: 12, type: 'dot', start: { x: 61, y: 73 }, end: { x: 73, y: 87 }, svgPath: 'M 61 73 L 73 87', hintText: 'みぎしたへ てん' },
    ],
  },
  {
    id: 'yuki',
    character: '雪',
    category: 'nature',
    grade: 2,
    strokeCount: 11,
    readings: { onyomi: ['セツ'], kunyomi: ['ゆき'] },
    meaning: 'ふゆに ふる 白い ゆき',
    examples: [
      { word: '雪（ゆき）', reading: 'ゆき', sentence: '白い 雪が つもる。' },
      { word: '雪だるま（ゆきだるま）', reading: 'ゆきだるま', sentence: '公園で 雪だるまを 作る。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 28, y: 17 }, end: { x: 76, y: 13 }, svgPath: 'M 28 17 L 76 13', hintText: 'あめかんむり：うえの よこせん' },
      { strokeNumber: 2, type: 'vertical', start: { x: 18, y: 28 }, end: { x: 15, y: 43 }, svgPath: 'M 18 28 L 15 43', hintText: 'あめかんむり：ひだりの たてせん' },
      { strokeNumber: 3, type: 'hook', start: { x: 18, y: 30 }, end: { x: 80, y: 32 }, svgPath: 'M 18 30 L 82 24 L 80 32', hintText: 'あめかんむり：よこから みぎへ まがる' },
      { strokeNumber: 4, type: 'vertical', start: { x: 49, y: 17 }, end: { x: 50, y: 49 }, svgPath: 'M 49 17 L 50 49', hintText: 'あめかんむり：まんなかの たてせん' },
      { strokeNumber: 5, type: 'dot', start: { x: 30, y: 36 }, end: { x: 40, y: 40 }, svgPath: 'M 30 36 L 40 40', hintText: 'あめかんむり：ひだり うえの てん' },
      { strokeNumber: 6, type: 'dot', start: { x: 27, y: 43 }, end: { x: 38, y: 48 }, svgPath: 'M 27 43 L 38 48', hintText: 'あめかんむり：ひだり したの てん' },
      { strokeNumber: 7, type: 'dot', start: { x: 61, y: 31 }, end: { x: 71, y: 36 }, svgPath: 'M 61 31 L 71 36', hintText: 'あめかんむり：みぎ うえの てん' },
      { strokeNumber: 8, type: 'dot', start: { x: 61, y: 41 }, end: { x: 71, y: 46 }, svgPath: 'M 61 41 L 71 46', hintText: 'あめかんむり：みぎ したの てん' },
      { strokeNumber: 9, type: 'hook', start: { x: 27, y: 57 }, end: { x: 72, y: 82 }, svgPath: 'M 27 57 L 71 54 L 76 58 L 72 82', hintText: 'したの部分：うえから みぎへ、おおきく したへ まがる' },
      { strokeNumber: 10, type: 'horizontal', start: { x: 27, y: 70 }, end: { x: 74, y: 67 }, svgPath: 'M 27 70 L 74 67', hintText: 'したの部分：なかの よこせん' },
      { strokeNumber: 11, type: 'horizontal', start: { x: 26, y: 86 }, end: { x: 75, y: 83 }, svgPath: 'M 26 86 L 75 83', hintText: 'したの部分：いちばん したの よこせん' },
    ],
  },
  {
    id: 'hoshi',
    character: '星',
    category: 'nature',
    grade: 2,
    strokeCount: 9,
    readings: { onyomi: ['セイ', 'ショウ'], kunyomi: ['ほし'] },
    meaning: 'よぞらに かがやく ほし',
    examples: [
      { word: '星（ほし）', reading: 'ほし', sentence: 'きれいな 星が 光る。' },
      { word: '星空（ほしぞら）', reading: 'ほしぞら', sentence: '夏の 星空を ながめる。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'vertical', start: { x: 30, y: 15 }, end: { x: 30, y: 42 }, svgPath: 'M 30 15 L 30 42', hintText: '日の ひだり' },
      { strokeNumber: 2, type: 'hook', start: { x: 32, y: 17 }, end: { x: 70, y: 42 }, svgPath: 'M 32 17 L 70 17 L 70 42 L 64 42', hintText: '日の よこからたて' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 32, y: 30 }, end: { x: 68, y: 30 }, svgPath: 'M 32 30 L 68 30', hintText: '日の なか' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 32, y: 42 }, end: { x: 68, y: 42 }, svgPath: 'M 32 42 L 68 42', hintText: '日の した' },
      { strokeNumber: 5, type: 'left-sweep', start: { x: 48, y: 44 }, end: { x: 26, y: 65 }, svgPath: 'M 48 44 L 26 65', hintText: 'ひだりへ はらう' },
      { strokeNumber: 6, type: 'horizontal', start: { x: 28, y: 58 }, end: { x: 74, y: 58 }, svgPath: 'M 28 58 L 74 58', hintText: 'よこへ まっすぐ' },
      { strokeNumber: 7, type: 'vertical', start: { x: 50, y: 44 }, end: { x: 50, y: 88 }, svgPath: 'M 50 44 L 50 88', hintText: 'たてへ ながく' },
      { strokeNumber: 8, type: 'horizontal', start: { x: 30, y: 72 }, end: { x: 70, y: 72 }, svgPath: 'M 30 72 L 70 72', hintText: 'よこせん' },
      { strokeNumber: 9, type: 'horizontal', start: { x: 18, y: 88 }, end: { x: 82, y: 88 }, svgPath: 'M 18 88 L 82 88', hintText: 'したの ながいよこせん' },
    ],
  },
  {
    id: 'haru',
    character: '春',
    category: 'nature',
    grade: 2,
    strokeCount: 9,
    readings: { onyomi: ['シュン'], kunyomi: ['はる'] },
    meaning: 'あたたかい はるの きせつ',
    examples: [
      { word: '春（はる）', reading: 'はる', sentence: 'あたたかい 春が やってくる。' },
      { word: '春休み（はるやすみ）', reading: 'はるやすみ', sentence: '春休みに おじいちゃんに 会う。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 30, y: 18 }, end: { x: 70, y: 18 }, svgPath: 'M 30 18 L 70 18', hintText: 'うえの よこせん' },
      { strokeNumber: 2, type: 'horizontal', start: { x: 22, y: 32 }, end: { x: 78, y: 32 }, svgPath: 'M 22 32 L 78 32', hintText: '２ばんめの よこせん' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 14, y: 48 }, end: { x: 86, y: 48 }, svgPath: 'M 14 48 L 86 48', hintText: 'いちばん ながい よこせん' },
      { strokeNumber: 4, type: 'left-sweep', start: { x: 50, y: 18 }, end: { x: 18, y: 78 }, svgPath: 'M 50 18 C 45 45, 35 65, 18 78', hintText: 'ひだりへ ながく はらう' },
      { strokeNumber: 5, type: 'dot', start: { x: 50, y: 32 }, end: { x: 82, y: 78 }, svgPath: 'M 50 32 C 60 50, 70 65, 82 78', hintText: 'みぎへ ながく はらう' },
      { strokeNumber: 6, type: 'vertical', start: { x: 34, y: 64 }, end: { x: 34, y: 88 }, svgPath: 'M 34 64 L 34 88', hintText: '日の ひだり' },
      { strokeNumber: 7, type: 'hook', start: { x: 36, y: 64 }, end: { x: 66, y: 88 }, svgPath: 'M 36 64 L 66 64 L 66 88 L 60 88', hintText: '日の よこからたて' },
      { strokeNumber: 8, type: 'horizontal', start: { x: 36, y: 76 }, end: { x: 64, y: 76 }, svgPath: 'M 36 76 L 64 76', hintText: '日の なか' },
      { strokeNumber: 9, type: 'horizontal', start: { x: 36, y: 88 }, end: { x: 64, y: 88 }, svgPath: 'M 36 88 L 64 88', hintText: '日の した' },
    ],
  },

  // === 学校と勉強 ===
  {
    id: 'gaku',
    character: '学',
    category: 'school',
    grade: 2,
    strokeCount: 8,
    readings: { onyomi: ['ガク'], kunyomi: ['まな（ぶ）'] },
    meaning: 'がっこうで まなぶ',
    examples: [
      { word: '学校（がっこう）', reading: 'がっこう', sentence: '毎日 元気に 学校へ 行く。' },
      { word: '学習（がくしゅう）', reading: 'がくしゅう', sentence: '漢字を 学習する。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'dot', start: { x: 26, y: 16 }, end: { x: 32, y: 24 }, svgPath: 'M 26 16 L 32 24', hintText: 'ひだりのてん' },
      { strokeNumber: 2, type: 'dot', start: { x: 50, y: 14 }, end: { x: 50, y: 22 }, svgPath: 'M 50 14 L 50 22', hintText: 'まんなかのてん' },
      { strokeNumber: 3, type: 'left-sweep', start: { x: 74, y: 16 }, end: { x: 68, y: 24 }, svgPath: 'M 74 16 L 68 24', hintText: 'みぎのてん' },
      { strokeNumber: 4, type: 'dot', start: { x: 18, y: 32 }, end: { x: 24, y: 44 }, svgPath: 'M 18 32 L 24 44', hintText: 'わかんむり ひだり' },
      { strokeNumber: 5, type: 'hook', start: { x: 20, y: 34 }, end: { x: 82, y: 46 }, svgPath: 'M 20 34 L 82 34 L 82 46 L 74 46', hintText: 'よこから したへまがる' },
      { strokeNumber: 6, type: 'hook', start: { x: 42, y: 48 }, end: { x: 62, y: 62 }, svgPath: 'M 42 48 L 62 48 L 62 62 L 54 62', hintText: '子の うえ' },
      { strokeNumber: 7, type: 'curve', start: { x: 52, y: 58 }, end: { x: 48, y: 92 }, svgPath: 'M 52 58 C 54 75, 52 88, 48 92 C 45 94, 40 90, 38 86', hintText: '子の たてから はねる' },
      { strokeNumber: 8, type: 'horizontal', start: { x: 24, y: 72 }, end: { x: 76, y: 72 }, svgPath: 'M 24 72 L 76 72', hintText: 'よこへ まっすぐ' },
    ],
  },
  {
    id: 'kou',
    character: '校',
    category: 'school',
    grade: 2,
    strokeCount: 10,
    readings: { onyomi: ['コウ'], kunyomi: [] },
    meaning: 'がっこう・まなびや',
    examples: [
      { word: '学校（がっこう）', reading: 'がっこう', sentence: '楽しい 学校生活。' },
      { word: '校長先生（こうちょうせんせい）', reading: 'こうちょうせんせい', sentence: '校長先生の お話を聞く。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 14, y: 38 }, end: { x: 38, y: 38 }, svgPath: 'M 14 38 L 38 38', hintText: 'きへんの よこ' },
      { strokeNumber: 2, type: 'vertical', start: { x: 26, y: 16 }, end: { x: 26, y: 88 }, svgPath: 'M 26 16 L 26 88', hintText: 'きへんの たて' },
      { strokeNumber: 3, type: 'left-sweep', start: { x: 26, y: 38 }, end: { x: 14, y: 74 }, svgPath: 'M 26 38 L 14 74', hintText: 'ひだりへ はらう' },
      { strokeNumber: 4, type: 'dot', start: { x: 28, y: 46 }, end: { x: 38, y: 56 }, svgPath: 'M 28 46 L 38 56', hintText: 'みぎの てん' },
      { strokeNumber: 5, type: 'vertical', start: { x: 61, y: 14 }, end: { x: 62, y: 27 }, svgPath: 'M 61 14 L 62 27', hintText: 'うえの みじかい たて' },
      { strokeNumber: 6, type: 'horizontal', start: { x: 44, y: 29 }, end: { x: 84, y: 26 }, svgPath: 'M 44 29 L 84 26', hintText: 'よこせん' },
      { strokeNumber: 7, type: 'left-sweep', start: { x: 54, y: 36 }, end: { x: 46, y: 48 }, svgPath: 'M 54 36 L 46 48', hintText: 'みじかく ひだりしたへ はらう' },
      { strokeNumber: 8, type: 'dot', start: { x: 73, y: 35 }, end: { x: 83, y: 47 }, svgPath: 'M 73 35 L 83 47', hintText: 'みぎうえの てん' },
      { strokeNumber: 9, type: 'left-sweep', start: { x: 73, y: 45 }, end: { x: 40, y: 84 }, svgPath: 'M 73 45 C 65 58, 55 70, 40 84', hintText: 'みぎうえから ひだりしたへ おおきく はらう' },
      { strokeNumber: 10, type: 'right-sweep', start: { x: 51, y: 51 }, end: { x: 88, y: 83 }, svgPath: 'M 51 51 C 60 60, 72 70, 88 83', hintText: 'ひだりから みぎしたへ ながく はらう' },
    ],
  },
  {
    id: 'kaku',
    character: '書',
    category: 'school',
    grade: 2,
    strokeCount: 10,
    readings: { onyomi: ['ショ'], kunyomi: ['か（く）'] },
    meaning: 'もじを かく',
    examples: [
      { word: '書く（かく）', reading: 'かく', sentence: 'ノートに 漢字を 書く。' },
      { word: '教科書（きょうかしょ）', reading: 'きょうかしょ', sentence: '国語の 教科書を読む。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'hook', start: { x: 28, y: 19 }, end: { x: 68, y: 34 }, svgPath: 'M 28 19 L 71 19 L 68 34', hintText: 'うえの よこせんから みぎしたへ まがる' },
      { strokeNumber: 2, type: 'horizontal', start: { x: 11, y: 30 }, end: { x: 90, y: 26 }, svgPath: 'M 11 30 L 90 26', hintText: '２ばんめの ながい よこせん' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 27, y: 38 }, end: { x: 70, y: 36 }, svgPath: 'M 27 38 L 70 36', hintText: '３ばんめの よこせん' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 28, y: 48 }, end: { x: 71, y: 45 }, svgPath: 'M 28 48 L 71 45', hintText: '４ばんめの よこせん' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 16, y: 58 }, end: { x: 85, y: 55 }, svgPath: 'M 16 58 L 85 55', hintText: '５ばんめの ながい よこせん' },
      { strokeNumber: 6, type: 'vertical', start: { x: 48, y: 9 }, end: { x: 50, y: 55 }, svgPath: 'M 48 9 L 50 55', hintText: 'うえから したまで つらぬく たてせん' },
      { strokeNumber: 7, type: 'vertical', start: { x: 29, y: 66 }, end: { x: 33, y: 91 }, svgPath: 'M 29 66 L 33 91', hintText: '日の ひだり' },
      { strokeNumber: 8, type: 'hook', start: { x: 31, y: 68 }, end: { x: 71, y: 89 }, svgPath: 'M 31 68 L 74 64 L 75 72 L 71 89', hintText: '日の よこから みぎしたへ まがる' },
      { strokeNumber: 9, type: 'horizontal', start: { x: 33, y: 77 }, end: { x: 74, y: 74 }, svgPath: 'M 33 77 L 74 74', hintText: '日の なか' },
      { strokeNumber: 10, type: 'horizontal', start: { x: 34, y: 87 }, end: { x: 71, y: 86 }, svgPath: 'M 34 87 L 71 86', hintText: '日の した' },
    ],
  },
  {
    id: 'yomu',
    character: '読',
    category: 'school',
    grade: 2,
    strokeCount: 14,
    readings: { onyomi: ['ドク'], kunyomi: ['よ（む）'] },
    meaning: 'ほんや もじを よむ',
    examples: [
      { word: '読む（よむ）', reading: 'よむ', sentence: 'としょかんで 本を 読む。' },
      { word: '読書（どくしょ）', reading: 'どくしょ', sentence: '休みの日に 読書を する。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'dot', start: { x: 26, y: 16 }, end: { x: 30, y: 22 }, svgPath: 'M 26 16 L 30 22', hintText: 'ごんべん の てん' },
      { strokeNumber: 2, type: 'horizontal', start: { x: 14, y: 30 }, end: { x: 42, y: 30 }, svgPath: 'M 14 30 L 42 30', hintText: 'ごんべん よこ１' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 18, y: 42 }, end: { x: 38, y: 42 }, svgPath: 'M 18 42 L 38 42', hintText: 'ごんべん よこ２' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 18, y: 54 }, end: { x: 38, y: 54 }, svgPath: 'M 18 54 L 38 54', hintText: 'ごんべん よこ３' },
      { strokeNumber: 5, type: 'vertical', start: { x: 18, y: 66 }, end: { x: 18, y: 88 }, svgPath: 'M 18 66 L 18 88', hintText: 'ごんべん 口ひだり' },
      { strokeNumber: 6, type: 'hook', start: { x: 20, y: 68 }, end: { x: 38, y: 88 }, svgPath: 'M 20 68 L 38 68 L 38 88 L 34 88', hintText: 'ごんべん 口みぎ' },
      { strokeNumber: 7, type: 'horizontal', start: { x: 20, y: 88 }, end: { x: 38, y: 88 }, svgPath: 'M 20 88 L 38 88', hintText: 'ごんべん 口した' },
      { strokeNumber: 8, type: 'horizontal', start: { x: 50, y: 20 }, end: { x: 86, y: 20 }, svgPath: 'M 50 20 L 86 20', hintText: 'みぎ うえよこ' },
      { strokeNumber: 9, type: 'vertical', start: { x: 68, y: 20 }, end: { x: 68, y: 38 }, svgPath: 'M 68 20 L 68 38', hintText: 'みぎ たて' },
      { strokeNumber: 10, type: 'horizontal', start: { x: 48, y: 40 }, end: { x: 88, y: 40 }, svgPath: 'M 48 40 L 88 40', hintText: 'みぎ ながいよこ' },
      { strokeNumber: 11, type: 'dot', start: { x: 42, y: 44 }, end: { x: 40, y: 57 }, svgPath: 'M 42 44 L 40 57', hintText: 'みじかく したへ' },
      { strokeNumber: 12, type: 'hook', start: { x: 43, y: 46 }, end: { x: 80, y: 50 }, svgPath: 'M 43 46 L 81 42 L 84 45 L 80 50', hintText: 'よこせんから みぎしたへ おれる' },
      { strokeNumber: 13, type: 'left-sweep', start: { x: 55, y: 54 }, end: { x: 41, y: 87 }, svgPath: 'M 55 54 C 50 65, 45 76, 41 87', hintText: 'みぎうえから ひだりしたへ ながく はらう' },
      { strokeNumber: 14, type: 'hook', start: { x: 66, y: 52 }, end: { x: 88, y: 81 }, svgPath: 'M 66 52 L 67 81 C 68 86, 78 88, 88 81', hintText: 'したへ おりて、みぎへ まがる' },
    ],
  },

  // === 家族と人 ===
  {
    id: 'chichi',
    character: '父',
    category: 'family',
    grade: 2,
    strokeCount: 4,
    readings: { onyomi: ['フ'], kunyomi: ['ちち', 'とう'] },
    meaning: 'おとうさん',
    examples: [
      { word: '父（ちち）', reading: 'ちち', sentence: '父と キャッチボールをする。' },
      { word: 'お父さん（おとうさん）', reading: 'おとうさん', sentence: 'お父さんの お手伝い。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'dot', start: { x: 34, y: 20 }, end: { x: 26, y: 36 }, svgPath: 'M 34 20 L 26 36', hintText: 'ひだり上の てん' },
      { strokeNumber: 2, type: 'dot', start: { x: 66, y: 20 }, end: { x: 74, y: 34 }, svgPath: 'M 66 20 L 74 34', hintText: 'みぎ上の てん' },
      { strokeNumber: 3, type: 'left-sweep', start: { x: 58, y: 38 }, end: { x: 22, y: 84 }, svgPath: 'M 58 38 C 50 60, 36 76, 22 84', hintText: 'ながく ひだりへ はらう' },
      { strokeNumber: 4, type: 'dot', start: { x: 42, y: 46 }, end: { x: 82, y: 84 }, svgPath: 'M 42 46 C 56 66, 68 76, 82 84', hintText: 'ながく みぎへ はらう' },
    ],
  },
  {
    id: 'haha',
    character: '母',
    category: 'family',
    grade: 2,
    strokeCount: 5,
    readings: { onyomi: ['ボ'], kunyomi: ['はは', 'かあ'] },
    meaning: 'おかあさん',
    examples: [
      { word: '母（はは）', reading: 'はは', sentence: '母に プレゼントを あげる。' },
      { word: 'お母さん（おかあさん）', reading: 'おかあさん', sentence: 'お母さんと 買い物へいく。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'hook', start: { x: 32, y: 18 }, end: { x: 74, y: 82 }, svgPath: 'M 32 18 C 28 35, 23 55, 23 68 C 35 70, 55 76, 74 82', hintText: 'ひだりたてから したへ、みぎへ おおきく はらう' },
      { strokeNumber: 2, type: 'hook', start: { x: 34, y: 20 }, end: { x: 50, y: 82 }, svgPath: 'M 34 20 L 75 20 C 72 45, 65 68, 50 82', hintText: 'よこから みぎしたへ まがる' },
      { strokeNumber: 3, type: 'dot', start: { x: 45, y: 26 }, end: { x: 55, y: 36 }, svgPath: 'M 45 26 L 55 36', hintText: 'うえの てん' },
      { strokeNumber: 4, type: 'dot', start: { x: 42, y: 53 }, end: { x: 51, y: 63 }, svgPath: 'M 42 53 L 51 63', hintText: 'したの てん' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 9, y: 47 }, end: { x: 90, y: 43 }, svgPath: 'M 9 47 L 90 43', hintText: 'ながい よこせん' },
    ],
  },
  {
    id: 'tomo',
    character: '友',
    category: 'family',
    grade: 2,
    strokeCount: 4,
    readings: { onyomi: ['ユウ'], kunyomi: ['とも'] },
    meaning: 'おともだち・なかま',
    examples: [
      { word: '友だち（ともだち）', reading: 'ともだち', sentence: '友だちと 公園で あそぶ。' },
      { word: '親友（しんゆう）', reading: 'しんゆう', sentence: '大すきな 親友がいる。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 22, y: 28 }, end: { x: 78, y: 28 }, svgPath: 'M 22 28 L 78 28', hintText: 'うえの よこせん' },
      { strokeNumber: 2, type: 'left-sweep', start: { x: 50, y: 16 }, end: { x: 20, y: 82 }, svgPath: 'M 50 16 C 45 44, 34 68, 20 82', hintText: 'うえから ながく ひだりはらい' },
      { strokeNumber: 3, type: 'hook', start: { x: 39, y: 50 }, end: { x: 22, y: 89 }, svgPath: 'M 39 50 L 65 52 C 55 65, 40 78, 22 89', hintText: 'よこから みぎへ、そして ひだりしたへ ながく' },
      { strokeNumber: 4, type: 'dot', start: { x: 46, y: 58 }, end: { x: 84, y: 86 }, svgPath: 'M 46 58 C 58 72, 70 80, 84 86', hintText: 'みぎへ ながく はらう' },
    ],
  },
  {
    id: 'ani',
    character: '兄',
    category: 'family',
    grade: 2,
    strokeCount: 5,
    readings: { onyomi: ['キョウ', 'ケイ'], kunyomi: ['あに', 'にい'] },
    meaning: 'おにいさん',
    examples: [
      { word: '兄（あに）', reading: 'あに', sentence: '兄と いっしょに 学校へ 行く。' },
      { word: 'お兄さん（おにいさん）', reading: 'おにいさん', sentence: 'やさしい お兄さん。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'vertical', start: { x: 30, y: 18 }, end: { x: 30, y: 48 }, svgPath: 'M 30 18 L 30 48', hintText: '口の ひだり' },
      { strokeNumber: 2, type: 'hook', start: { x: 32, y: 20 }, end: { x: 70, y: 48 }, svgPath: 'M 32 20 L 70 20 L 70 48 L 64 48', hintText: '口の よこからたて' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 30, y: 48 }, end: { x: 70, y: 48 }, svgPath: 'M 30 48 L 70 48', hintText: '口の した' },
      { strokeNumber: 4, type: 'left-sweep', start: { x: 45, y: 50 }, end: { x: 22, y: 88 }, svgPath: 'M 45 50 C 40 68, 32 80, 22 88', hintText: 'ひだりへ ながくはらう' },
      { strokeNumber: 5, type: 'hook', start: { x: 58, y: 50 }, end: { x: 80, y: 86 }, svgPath: 'M 58 50 L 58 78 C 58 86, 68 86, 80 86 L 80 78', hintText: 'みぎしたへ まがってはねる' },
    ],
  },
  {
    id: 'imouto',
    character: '妹',
    category: 'family',
    grade: 2,
    strokeCount: 8,
    readings: { onyomi: ['マイ'], kunyomi: ['いもうと'] },
    meaning: 'いもうと',
    examples: [
      { word: '妹（いもうと）', reading: 'いもうと', sentence: '妹と 仲よく あそぶ。' },
      { word: '姉妹（しまい）', reading: 'しまい', sentence: '仲のよい 姉妹。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'hook', start: { x: 24, y: 17 }, end: { x: 36, y: 71 }, svgPath: 'M 24 17 C 22 30, 19 45, 19 56 C 22 62, 29 66, 36 71', hintText: 'おんなへん １' },
      { strokeNumber: 2, type: 'left-sweep', start: { x: 36, y: 32 }, end: { x: 16, y: 76 }, svgPath: 'M 36 32 C 30 54, 24 66, 16 76', hintText: 'おんなへん ２' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 12, y: 52 }, end: { x: 44, y: 44 }, svgPath: 'M 12 52 L 44 44', hintText: 'おんなへん ３（よこせん）' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 52, y: 28 }, end: { x: 86, y: 28 }, svgPath: 'M 52 28 L 86 28', hintText: 'みぎの うえよこ' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 44, y: 48 }, end: { x: 92, y: 48 }, svgPath: 'M 44 48 L 92 48', hintText: 'みぎの ながいよこ' },
      { strokeNumber: 6, type: 'vertical', start: { x: 68, y: 16 }, end: { x: 68, y: 88 }, svgPath: 'M 68 16 L 68 88', hintText: 'まんなかの たて' },
      { strokeNumber: 7, type: 'left-sweep', start: { x: 68, y: 48 }, end: { x: 33, y: 80 }, svgPath: 'M 68 48 L 33 80', hintText: 'ひだりへ はらう' },
      { strokeNumber: 8, type: 'dot', start: { x: 68, y: 48 }, end: { x: 88, y: 80 }, svgPath: 'M 68 48 L 88 80', hintText: 'みぎへ はらう' },
    ],
  },

  // === 時間と日にち ===
  {
    id: 'jikan',
    character: '時',
    category: 'time',
    grade: 2,
    strokeCount: 10,
    readings: { onyomi: ['ジ'], kunyomi: ['とき'] },
    meaning: 'じかん・とき',
    examples: [
      { word: '時間（じかん）', reading: 'じかん', sentence: 'おやつの 時間が 来た。' },
      { word: '時計（とけい）', reading: 'とけい', sentence: '時計を見て 朝おきる。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'vertical', start: { x: 16, y: 24 }, end: { x: 16, y: 80 }, svgPath: 'M 16 24 L 16 80', hintText: 'ひだり（日）の たて' },
      { strokeNumber: 2, type: 'hook', start: { x: 18, y: 26 }, end: { x: 38, y: 80 }, svgPath: 'M 18 26 L 38 26 L 38 80 L 32 80', hintText: 'ひだり（日）の まがり' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 18, y: 52 }, end: { x: 36, y: 52 }, svgPath: 'M 18 52 L 36 52', hintText: 'ひだり（日）の なか' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 18, y: 78 }, end: { x: 36, y: 78 }, svgPath: 'M 18 78 L 36 78', hintText: 'ひだり（日）の した' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 52, y: 24 }, end: { x: 84, y: 24 }, svgPath: 'M 52 24 L 84 24', hintText: 'みぎ（寺）の うえよこ' },
      { strokeNumber: 6, type: 'vertical', start: { x: 68, y: 14 }, end: { x: 68, y: 44 }, svgPath: 'M 68 14 L 68 44', hintText: 'みぎの たてせん' },
      { strokeNumber: 7, type: 'horizontal', start: { x: 44, y: 44 }, end: { x: 90, y: 44 }, svgPath: 'M 44 44 L 90 44', hintText: 'みぎの ながいよこ' },
      { strokeNumber: 8, type: 'horizontal', start: { x: 42, y: 56 }, end: { x: 88, y: 53 }, svgPath: 'M 42 56 L 88 53', hintText: '寸の よこせん' },
      { strokeNumber: 9, type: 'hook', start: { x: 78, y: 44 }, end: { x: 78, y: 88 }, svgPath: 'M 78 44 L 78 88 C 76 92, 70 90, 66 84', hintText: '寸の たてからはねる' },
      { strokeNumber: 10, type: 'dot', start: { x: 58, y: 70 }, end: { x: 66, y: 76 }, svgPath: 'M 58 70 L 66 76', hintText: '寸の てん' },
    ],
  },
  {
    id: 'asa',
    character: '朝',
    category: 'time',
    grade: 2,
    strokeCount: 12,
    readings: { onyomi: ['チョウ'], kunyomi: ['あさ'] },
    meaning: 'いちにちの はじまりの じかん',
    examples: [
      { word: '朝（あさ）', reading: 'あさ', sentence: '朝、元気に あいさつをする。' },
      { word: '朝ごはん（あさごはん）', reading: 'あさごはん', sentence: 'おいしい 朝ごはんを 食べる。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 15, y: 25 }, end: { x: 49, y: 22 }, svgPath: 'M 15 25 L 49 22', hintText: 'うえの じゅうじの よこ' },
      { strokeNumber: 2, type: 'vertical', start: { x: 31, y: 11 }, end: { x: 33, y: 33 }, svgPath: 'M 31 11 L 33 33', hintText: 'うえの じゅうじの たて' },
      { strokeNumber: 3, type: 'vertical', start: { x: 16, y: 35 }, end: { x: 21, y: 58 }, svgPath: 'M 16 35 L 21 58', hintText: '日の ひだり' },
      { strokeNumber: 4, type: 'hook', start: { x: 19, y: 36 }, end: { x: 45, y: 56 }, svgPath: 'M 19 36 L 49 36 L 48 43 L 45 56', hintText: '日の よこからたて' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 21, y: 46 }, end: { x: 46, y: 43 }, svgPath: 'M 21 46 L 46 43', hintText: '日の なか' },
      { strokeNumber: 6, type: 'horizontal', start: { x: 22, y: 56 }, end: { x: 45, y: 53 }, svgPath: 'M 22 56 L 45 53', hintText: '日の した' },
      { strokeNumber: 7, type: 'horizontal', start: { x: 9, y: 69 }, end: { x: 53, y: 65 }, svgPath: 'M 9 69 L 53 65', hintText: 'したの じゅうじの よこ' },
      { strokeNumber: 8, type: 'vertical', start: { x: 32, y: 57 }, end: { x: 33, y: 87 }, svgPath: 'M 32 57 L 33 87', hintText: 'したの じゅうじの たて' },
      { strokeNumber: 9, type: 'left-sweep', start: { x: 60, y: 19 }, end: { x: 50, y: 85 }, svgPath: 'M 60 19 C 62 40, 61 60, 55 78 C 53 81, 51 83, 50 85', hintText: '月（つき）の ひだりを ながく はらう' },
      { strokeNumber: 10, type: 'hook', start: { x: 62, y: 20 }, end: { x: 78, y: 84 }, svgPath: 'M 62 20 L 86 20 L 86 85 L 78 84', hintText: '月 の よこからたてはね' },
      { strokeNumber: 11, type: 'horizontal', start: { x: 63, y: 37 }, end: { x: 84, y: 35 }, svgPath: 'M 63 37 L 84 35', hintText: '月の なか１' },
      { strokeNumber: 12, type: 'horizontal', start: { x: 62, y: 56 }, end: { x: 84, y: 54 }, svgPath: 'M 62 56 L 84 54', hintText: '月の なか２' },
    ],
  },
  {
    id: 'haru_now',
    character: '今',
    category: 'time',
    grade: 2,
    strokeCount: 4,
    readings: { onyomi: ['コン', 'キン'], kunyomi: ['いま'] },
    meaning: 'いま・現在',
    examples: [
      { word: '今（いま）', reading: 'いま', sentence: '今は 学校が 休みです。' },
      { word: '今日（きょう）', reading: 'きょう', sentence: '今日は いい お天気です。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'left-sweep', start: { x: 45, y: 13 }, end: { x: 11, y: 57 }, svgPath: 'M 45 13 C 40 26, 32 40, 22 50 C 18 53, 14 55, 11 57', hintText: 'うえから ひだりへ はらう' },
      { strokeNumber: 2, type: 'dot', start: { x: 46, y: 17 }, end: { x: 89, y: 54 }, svgPath: 'M 46 17 C 56 27, 67 37, 77 47 C 81 50, 85 52, 89 54', hintText: 'みぎへ ながく はらう' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 36, y: 46 }, end: { x: 59, y: 44 }, svgPath: 'M 36 46 L 59 44', hintText: 'なかの よこせん' },
      { strokeNumber: 4, type: 'hook', start: { x: 31, y: 62 }, end: { x: 49, y: 87 }, svgPath: 'M 31 62 L 62 59 C 61 66, 58 73, 53 80 C 51 83, 50 85, 49 87', hintText: 'よこから したへ まがる' },
    ],
  },

  // === 動物・植物・食べ物 ===
  {
    id: 'inu',
    character: '犬',
    category: 'animals',
    grade: 2,
    strokeCount: 4,
    readings: { onyomi: ['ケン'], kunyomi: ['いぬ'] },
    meaning: 'どうぶつの いぬ',
    examples: [
      { word: '犬（いぬ）', reading: 'いぬ', sentence: 'かわいい 犬と さんぽする。' },
      { word: '子犬（こいぬ）', reading: 'こいぬ', sentence: '元気な 子犬。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 20, y: 38 }, end: { x: 80, y: 38 }, svgPath: 'M 20 38 L 80 38', hintText: 'よこへ まっすぐ' },
      { strokeNumber: 2, type: 'left-sweep', start: { x: 50, y: 16 }, end: { x: 22, y: 84 }, svgPath: 'M 50 16 C 46 48, 36 70, 22 84', hintText: 'うえから ひだりへ ながくはらう' },
      { strokeNumber: 3, type: 'dot', start: { x: 48, y: 44 }, end: { x: 84, y: 84 }, svgPath: 'M 48 44 C 60 62, 72 74, 84 84', hintText: 'みぎしたへ ながくはらう' },
      { strokeNumber: 4, type: 'dot', start: { x: 68, y: 20 }, end: { x: 76, y: 28 }, svgPath: 'M 68 20 L 76 28', hintText: 'みぎうえに てん を うつ' },
    ],
  },
  {
    id: 'tori',
    character: '鳥',
    category: 'animals',
    grade: 2,
    strokeCount: 11,
    readings: { onyomi: ['チョウ'], kunyomi: ['とり'] },
    meaning: 'そらを とぶ とり',
    examples: [
      { word: '鳥（とり）', reading: 'とり', sentence: '白い 鳥が 空を とぶ。' },
      { word: '小鳥（ことり）', reading: 'ことり', sentence: '木の上で 小鳥が なく。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'left-sweep', start: { x: 50, y: 14 }, end: { x: 40, y: 24 }, svgPath: 'M 50 14 L 40 24', hintText: 'うえの ひだりはらい' },
      { strokeNumber: 2, type: 'vertical', start: { x: 30, y: 26 }, end: { x: 30, y: 64 }, svgPath: 'M 30 26 L 30 64', hintText: 'ひだりの たてせん' },
      { strokeNumber: 3, type: 'hook', start: { x: 32, y: 28 }, end: { x: 74, y: 42 }, svgPath: 'M 32 28 L 74 28 L 74 42 L 68 42', hintText: 'よこから したへ' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 33, y: 33 }, end: { x: 61, y: 28 }, svgPath: 'M 33 33 L 61 28', hintText: 'よこせん１' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 33, y: 42 }, end: { x: 59, y: 38 }, svgPath: 'M 33 42 L 59 38', hintText: 'よこせん２' },
      { strokeNumber: 6, type: 'horizontal', start: { x: 33, y: 51 }, end: { x: 76, y: 46 }, svgPath: 'M 33 51 L 76 46', hintText: 'ながい よこせん' },
      { strokeNumber: 7, type: 'hook', start: { x: 32, y: 63 }, end: { x: 65, y: 85 }, svgPath: 'M 32 63 L 77 57 C 83 64, 82 70, 79 75 C 77 81, 71 85, 65 85', hintText: 'よこから みぎへ、おおきく したへ まがる' },
      { strokeNumber: 8, type: 'dot', start: { x: 26, y: 78 }, end: { x: 24, y: 88 }, svgPath: 'M 26 78 L 24 88', hintText: 'れっか てん１' },
      { strokeNumber: 9, type: 'dot', start: { x: 38, y: 78 }, end: { x: 40, y: 88 }, svgPath: 'M 38 78 L 40 88', hintText: 'れっか てん２' },
      { strokeNumber: 10, type: 'dot', start: { x: 50, y: 78 }, end: { x: 54, y: 88 }, svgPath: 'M 50 78 L 54 88', hintText: 'れっか てん３' },
      { strokeNumber: 11, type: 'dot', start: { x: 62, y: 78 }, end: { x: 68, y: 88 }, svgPath: 'M 62 78 L 68 88', hintText: 'れっか てん４' },
    ],
  },
  {
    id: 'ushi',
    character: '牛',
    category: 'animals',
    grade: 2,
    strokeCount: 4,
    readings: { onyomi: ['ギュウ'], kunyomi: ['うし'] },
    meaning: 'どうぶつの うし',
    examples: [
      { word: '牛（うし）', reading: 'うし', sentence: '牧場（ぼくじょう）で 牛を見る。' },
      { word: '牛乳（ぎゅうにゅう）', reading: 'ぎゅうにゅう', sentence: 'おいしい 牛乳を 飲む。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'left-sweep', start: { x: 44, y: 18 }, end: { x: 28, y: 32 }, svgPath: 'M 44 18 L 28 32', hintText: 'ひだりうえのはらい' },
      { strokeNumber: 2, type: 'horizontal', start: { x: 24, y: 40 }, end: { x: 76, y: 40 }, svgPath: 'M 24 40 L 76 40', hintText: 'よこせん' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 16, y: 64 }, end: { x: 84, y: 64 }, svgPath: 'M 16 64 L 84 64', hintText: 'ながい よこせん' },
      { strokeNumber: 4, type: 'vertical', start: { x: 50, y: 22 }, end: { x: 50, y: 88 }, svgPath: 'M 50 22 L 50 88', hintText: 'まんなかの たてせん' },
    ],
  },
  {
    id: 'sakana',
    character: '魚',
    category: 'animals',
    grade: 2,
    strokeCount: 11,
    readings: { onyomi: ['ギョ'], kunyomi: ['さかな', 'うお'] },
    meaning: 'うみや かわの さかな',
    examples: [
      { word: '魚（さかな）', reading: 'さかな', sentence: '川で 魚を つる。' },
      { word: '金魚（きんぎょ）', reading: 'きんぎょ', sentence: '赤い 金魚が およぐ。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'left-sweep', start: { x: 50, y: 14 }, end: { x: 38, y: 26 }, svgPath: 'M 50 14 L 38 26', hintText: 'クの ひだりはらい' },
      { strokeNumber: 2, type: 'hook', start: { x: 42, y: 20 }, end: { x: 66, y: 28 }, svgPath: 'M 42 20 L 66 20 L 58 28', hintText: 'クの みぎ' },
      { strokeNumber: 3, type: 'vertical', start: { x: 24, y: 34 }, end: { x: 24, y: 70 }, svgPath: 'M 24 34 L 24 70', hintText: '田の ひだりたて' },
      { strokeNumber: 4, type: 'hook', start: { x: 26, y: 36 }, end: { x: 76, y: 70 }, svgPath: 'M 26 36 L 76 36 L 76 70', hintText: '田の みぎまがり' },
      { strokeNumber: 5, type: 'vertical', start: { x: 50, y: 36 }, end: { x: 50, y: 70 }, svgPath: 'M 50 36 L 50 70', hintText: '田の なかたて' },
      { strokeNumber: 6, type: 'horizontal', start: { x: 26, y: 52 }, end: { x: 74, y: 52 }, svgPath: 'M 26 52 L 74 52', hintText: '田の なかよこ' },
      { strokeNumber: 7, type: 'horizontal', start: { x: 26, y: 70 }, end: { x: 74, y: 70 }, svgPath: 'M 26 70 L 74 70', hintText: '田の したよこ' },
      { strokeNumber: 8, type: 'dot', start: { x: 26, y: 80 }, end: { x: 24, y: 88 }, svgPath: 'M 26 80 L 24 88', hintText: 'れっか てん１' },
      { strokeNumber: 9, type: 'dot', start: { x: 40, y: 80 }, end: { x: 42, y: 88 }, svgPath: 'M 40 80 L 42 88', hintText: 'れっか てん２' },
      { strokeNumber: 10, type: 'dot', start: { x: 56, y: 80 }, end: { x: 60, y: 88 }, svgPath: 'M 56 80 L 60 88', hintText: 'れっか てん３' },
      { strokeNumber: 11, type: 'dot', start: { x: 72, y: 80 }, end: { x: 78, y: 88 }, svgPath: 'M 72 80 L 78 88', hintText: 'れっか てん４' },
    ],
  },

  // === 街・場所・方角 ===
  {
    id: 'higashi',
    character: '東',
    category: 'places',
    grade: 2,
    strokeCount: 8,
    readings: { onyomi: ['トウ'], kunyomi: ['ひがし'] },
    meaning: 'ひがしの ほうがく',
    examples: [
      { word: '東（ひがし）', reading: 'ひがし', sentence: '東の 空から お日さまが出る。' },
      { word: '東京（とうきょう）', reading: 'とうきょう', sentence: '東京の おばあちゃんの家。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 24, y: 18 }, end: { x: 76, y: 18 }, svgPath: 'M 24 18 L 76 18', hintText: 'うえの よこせん' },
      { strokeNumber: 2, type: 'vertical', start: { x: 26, y: 32 }, end: { x: 26, y: 64 }, svgPath: 'M 26 32 L 26 64', hintText: '日の ひだり' },
      { strokeNumber: 3, type: 'hook', start: { x: 28, y: 34 }, end: { x: 74, y: 64 }, svgPath: 'M 28 34 L 74 34 L 74 64 L 68 64', hintText: '日の よこからたて' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 28, y: 48 }, end: { x: 72, y: 48 }, svgPath: 'M 28 48 L 72 48', hintText: '日の なか' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 28, y: 64 }, end: { x: 72, y: 64 }, svgPath: 'M 28 64 L 72 64', hintText: '日の した' },
      { strokeNumber: 6, type: 'vertical', start: { x: 50, y: 18 }, end: { x: 50, y: 88 }, svgPath: 'M 50 18 L 50 88', hintText: 'まんなかを つらぬく たて' },
      { strokeNumber: 7, type: 'left-sweep', start: { x: 48, y: 64 }, end: { x: 22, y: 86 }, svgPath: 'M 48 64 C 40 74, 30 80, 22 86', hintText: 'ひだりはらい' },
      { strokeNumber: 8, type: 'dot', start: { x: 52, y: 64 }, end: { x: 78, y: 86 }, svgPath: 'M 52 64 C 60 74, 70 80, 78 86', hintText: 'みぎはらい' },
    ],
  },
  {
    id: 'nishi',
    character: '西',
    category: 'places',
    grade: 2,
    strokeCount: 6,
    readings: { onyomi: ['セイ', 'サイ'], kunyomi: ['にし'] },
    meaning: 'にしの ほうがく',
    examples: [
      { word: '西（にし）', reading: 'にし', sentence: '夕日（ゆうひ）が 西に しずむ。' },
      { word: '東西（とうざい）', reading: 'とうざい', sentence: '東西の 道。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 22, y: 20 }, end: { x: 78, y: 20 }, svgPath: 'M 22 20 L 78 20', hintText: 'うえの よこせん' },
      { strokeNumber: 2, type: 'vertical', start: { x: 20, y: 34 }, end: { x: 20, y: 84 }, svgPath: 'M 20 34 L 20 84', hintText: 'ひだりの たてせん' },
      { strokeNumber: 3, type: 'hook', start: { x: 22, y: 36 }, end: { x: 80, y: 84 }, svgPath: 'M 22 36 L 80 36 L 80 84 L 72 84', hintText: 'よこから たてへ' },
      { strokeNumber: 4, type: 'left-sweep', start: { x: 44, y: 40 }, end: { x: 38, y: 68 }, svgPath: 'M 44 40 C 42 54, 40 62, 38 68', hintText: 'なかの ひだり' },
      { strokeNumber: 5, type: 'hook', start: { x: 56, y: 40 }, end: { x: 64, y: 68 }, svgPath: 'M 56 40 C 58 54, 60 62, 64 68', hintText: 'なかの みぎ' },
      { strokeNumber: 6, type: 'horizontal', start: { x: 22, y: 84 }, end: { x: 78, y: 84 }, svgPath: 'M 22 84 L 78 84', hintText: 'したを まとめる よこせん' },
    ],
  },
  {
    id: 'minami',
    character: '南',
    category: 'places',
    grade: 2,
    strokeCount: 9,
    readings: { onyomi: ['ナン'], kunyomi: ['みなみ'] },
    meaning: 'あたたかい みなみ',
    examples: [
      { word: '南（みなみ）', reading: 'みなみ', sentence: 'あたたかい 南の しま。' },
      { word: '南北（なんぼく）', reading: 'なんぼく', sentence: '南北に 長い 日本。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 25, y: 26 }, end: { x: 75, y: 23 }, svgPath: 'M 25 26 L 75 23', hintText: 'うえの よこせん' },
      { strokeNumber: 2, type: 'vertical', start: { x: 48, y: 10 }, end: { x: 49, y: 40 }, svgPath: 'M 48 10 L 49 40', hintText: 'うえから なかへ おりる たて' },
      { strokeNumber: 3, type: 'vertical', start: { x: 19, y: 42 }, end: { x: 22, y: 87 }, svgPath: 'M 19 42 L 22 87', hintText: 'ひだりの たて' },
      { strokeNumber: 4, type: 'hook', start: { x: 21, y: 44 }, end: { x: 74, y: 84 }, svgPath: 'M 21 44 L 80 38 C 82 51, 83 66, 82 82 C 80 84, 77 84, 74 84', hintText: 'よこから したへはねる' },
      { strokeNumber: 5, type: 'dot', start: { x: 35, y: 45 }, end: { x: 42, y: 54 }, svgPath: 'M 35 45 L 42 54', hintText: 'なかの ひだりてん' },
      { strokeNumber: 6, type: 'dot', start: { x: 61, y: 42 }, end: { x: 56, y: 53 }, svgPath: 'M 61 42 L 56 53', hintText: 'なかの みぎてん' },
      { strokeNumber: 7, type: 'horizontal', start: { x: 32, y: 57 }, end: { x: 69, y: 55 }, svgPath: 'M 32 57 L 69 55', hintText: 'なかの よこせん１' },
      { strokeNumber: 8, type: 'horizontal', start: { x: 30, y: 68 }, end: { x: 71, y: 67 }, svgPath: 'M 30 68 L 71 67', hintText: 'なかの よこせん２' },
      { strokeNumber: 9, type: 'vertical', start: { x: 49, y: 57 }, end: { x: 50, y: 88 }, svgPath: 'M 49 57 L 50 88', hintText: 'なかの たてせん' },
    ],
  },
  {
    id: 'kita',
    character: '北',
    category: 'places',
    grade: 2,
    strokeCount: 5,
    readings: { onyomi: ['ホク'], kunyomi: ['きた'] },
    meaning: 'きたの ほうがく',
    examples: [
      { word: '北（きた）', reading: 'きた', sentence: '北の 国から 雪がふる。' },
      { word: '北風（きたかぜ）', reading: 'きたかぜ', sentence: 'つめたい 北風が ふく。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 18, y: 44 }, end: { x: 42, y: 44 }, svgPath: 'M 18 44 L 42 44', hintText: 'ひだりがわの よこ' },
      { strokeNumber: 2, type: 'vertical', start: { x: 38, y: 22 }, end: { x: 38, y: 84 }, svgPath: 'M 38 22 L 38 84', hintText: 'ひだりの たて' },
      { strokeNumber: 3, type: 'left-sweep', start: { x: 16, y: 78 }, end: { x: 34, y: 62 }, svgPath: 'M 16 78 L 34 62', hintText: 'したから はねる' },
      { strokeNumber: 4, type: 'left-sweep', start: { x: 74, y: 34 }, end: { x: 56, y: 52 }, svgPath: 'M 74 34 L 56 52', hintText: 'みぎがわの はらい' },
      { strokeNumber: 5, type: 'hook', start: { x: 55, y: 18 }, end: { x: 88, y: 70 }, svgPath: 'M 55 18 C 56 35, 57 52, 57 67 C 58 75, 65 80, 84 80 C 87 77, 88 74, 88 70', hintText: 'たてから したへ、みぎへ まがってはねる' },
    ],
  },

  // === うごきとことば ===
  {
    id: 'iku',
    character: '行',
    category: 'actions',
    grade: 2,
    strokeCount: 6,
    readings: { onyomi: ['コウ', 'ギョウ'], kunyomi: ['い（く）', 'ゆ（く）'] },
    meaning: 'あるいて いく・おこなう',
    examples: [
      { word: '行く（いく）', reading: 'いく', sentence: '元気に 学校へ 行く。' },
      { word: '旅行（りょこう）', reading: 'りょこう', sentence: '夏休みの 楽しい 旅行。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'left-sweep', start: { x: 36, y: 18 }, end: { x: 22, y: 40 }, svgPath: 'M 36 18 L 22 40', hintText: 'ぎょうにんべん うえ' },
      { strokeNumber: 2, type: 'left-sweep', start: { x: 38, y: 40 }, end: { x: 20, y: 68 }, svgPath: 'M 38 40 L 20 68', hintText: 'ぎょうにんべん なか' },
      { strokeNumber: 3, type: 'vertical', start: { x: 32, y: 54 }, end: { x: 32, y: 88 }, svgPath: 'M 32 54 L 32 88', hintText: 'ぎょうにんべん たて' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 46, y: 17 }, end: { x: 78, y: 15 }, svgPath: 'M 46 17 L 78 15', hintText: 'みぎの うえよこ' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 40, y: 38 }, end: { x: 88, y: 34 }, svgPath: 'M 40 38 L 88 34', hintText: 'みぎの したよこ' },
      { strokeNumber: 6, type: 'hook', start: { x: 74, y: 32 }, end: { x: 74, y: 88 }, svgPath: 'M 74 32 L 74 88 L 68 88', hintText: 'みぎの たてから はねる' },
    ],
  },
  {
    id: 'kuru',
    character: '来',
    category: 'actions',
    grade: 2,
    strokeCount: 7,
    readings: { onyomi: ['ライ'], kunyomi: ['く（る）', 'き（ます）'] },
    meaning: 'やって くる',
    examples: [
      { word: '来る（くる）', reading: 'くる', sentence: '友だちが 家に 来る。' },
      { word: '来週（らいしゅう）', reading: 'らいしゅう', sentence: '来週の えんそく。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'horizontal', start: { x: 28, y: 22 }, end: { x: 72, y: 22 }, svgPath: 'M 28 22 L 72 22', hintText: 'うえの よこせん' },
      { strokeNumber: 2, type: 'dot', start: { x: 34, y: 34 }, end: { x: 38, y: 44 }, svgPath: 'M 34 34 L 38 44', hintText: 'ひだりの てん' },
      { strokeNumber: 3, type: 'dot', start: { x: 66, y: 34 }, end: { x: 62, y: 44 }, svgPath: 'M 66 34 L 62 44', hintText: 'みぎの てん' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 16, y: 52 }, end: { x: 84, y: 52 }, svgPath: 'M 16 52 L 84 52', hintText: 'ながい よこせん' },
      { strokeNumber: 5, type: 'vertical', start: { x: 50, y: 14 }, end: { x: 50, y: 88 }, svgPath: 'M 50 14 L 50 88', hintText: 'まんなかの たてせん' },
      { strokeNumber: 6, type: 'left-sweep', start: { x: 50, y: 52 }, end: { x: 22, y: 84 }, svgPath: 'M 50 52 C 42 66, 32 76, 22 84', hintText: 'ひだりへ ながく はらう' },
      { strokeNumber: 7, type: 'dot', start: { x: 50, y: 52 }, end: { x: 78, y: 84 }, svgPath: 'M 50 52 C 58 66, 68 76, 78 84', hintText: 'みぎへ ながく はらう' },
    ],
  },
  {
    id: 'hanasu',
    character: '話',
    category: 'actions',
    grade: 2,
    strokeCount: 13,
    readings: { onyomi: ['ワ'], kunyomi: ['はな（す）', 'はなし'] },
    meaning: 'ことばで はなす',
    examples: [
      { word: '話す（はなす）', reading: 'はなす', sentence: '友だちと 楽しく 話す。' },
      { word: '会話（かいわ）', reading: 'かいわ', sentence: '英語の 会話練習。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'dot', start: { x: 26, y: 16 }, end: { x: 30, y: 22 }, svgPath: 'M 26 16 L 30 22', hintText: 'ごんべん てん' },
      { strokeNumber: 2, type: 'horizontal', start: { x: 14, y: 30 }, end: { x: 42, y: 30 }, svgPath: 'M 14 30 L 42 30', hintText: 'ごんべん よこ１' },
      { strokeNumber: 3, type: 'horizontal', start: { x: 18, y: 42 }, end: { x: 38, y: 42 }, svgPath: 'M 18 42 L 38 42', hintText: 'ごんべん よこ２' },
      { strokeNumber: 4, type: 'horizontal', start: { x: 18, y: 54 }, end: { x: 38, y: 54 }, svgPath: 'M 18 54 L 38 54', hintText: 'ごんべん よこ３' },
      { strokeNumber: 5, type: 'vertical', start: { x: 18, y: 66 }, end: { x: 18, y: 88 }, svgPath: 'M 18 66 L 18 88', hintText: 'ごんべん 口ひだり' },
      { strokeNumber: 6, type: 'hook', start: { x: 20, y: 68 }, end: { x: 38, y: 88 }, svgPath: 'M 20 68 L 38 68 L 38 88 L 34 88', hintText: 'ごんべん 口みぎ' },
      { strokeNumber: 7, type: 'horizontal', start: { x: 20, y: 88 }, end: { x: 38, y: 88 }, svgPath: 'M 20 88 L 38 88', hintText: 'ごんべん 口した' },
      { strokeNumber: 8, type: 'left-sweep', start: { x: 68, y: 14 }, end: { x: 54, y: 30 }, svgPath: 'M 68 14 L 54 30', hintText: '舌（した）の ひだりはらい' },
      { strokeNumber: 9, type: 'horizontal', start: { x: 48, y: 32 }, end: { x: 88, y: 32 }, svgPath: 'M 48 32 L 88 32', hintText: '舌（した）の よこせん' },
      { strokeNumber: 10, type: 'vertical', start: { x: 68, y: 32 }, end: { x: 68, y: 56 }, svgPath: 'M 68 32 L 68 56', hintText: '舌（した）の たてせん' },
      { strokeNumber: 11, type: 'vertical', start: { x: 54, y: 58 }, end: { x: 54, y: 88 }, svgPath: 'M 54 58 L 54 88', hintText: '口の ひだり' },
      { strokeNumber: 12, type: 'hook', start: { x: 56, y: 60 }, end: { x: 84, y: 88 }, svgPath: 'M 56 60 L 84 60 L 84 88 L 78 88', hintText: '口の よこからたて' },
      { strokeNumber: 13, type: 'horizontal', start: { x: 56, y: 88 }, end: { x: 84, y: 88 }, svgPath: 'M 56 88 L 84 88', hintText: '口の したよこ' },
    ],
  },
  {
    id: 'takai',
    character: '高',
    category: 'actions',
    grade: 2,
    strokeCount: 10,
    readings: { onyomi: ['コウ'], kunyomi: ['たか（い）'] },
    meaning: 'たかい・たかさ',
    examples: [
      { word: '高い（たかい）', reading: 'たかい', sentence: '背が 高い 木。' },
      { word: '高校（こうこう）', reading: 'こうこう', sentence: 'お兄ちゃんの 高校。' },
    ],
    strokes: [
      { strokeNumber: 1, type: 'dot', start: { x: 50, y: 14 }, end: { x: 50, y: 22 }, svgPath: 'M 50 14 L 50 22', hintText: 'うえの てん' },
      { strokeNumber: 2, type: 'horizontal', start: { x: 20, y: 24 }, end: { x: 80, y: 24 }, svgPath: 'M 20 24 L 80 24', hintText: 'よこせん' },
      { strokeNumber: 3, type: 'vertical', start: { x: 30, y: 34 }, end: { x: 30, y: 52 }, svgPath: 'M 30 34 L 30 52', hintText: 'うえの口の ひだり' },
      { strokeNumber: 4, type: 'hook', start: { x: 32, y: 36 }, end: { x: 70, y: 52 }, svgPath: 'M 32 36 L 70 36 L 70 52 L 64 52', hintText: 'うえの口の みぎ' },
      { strokeNumber: 5, type: 'horizontal', start: { x: 32, y: 52 }, end: { x: 70, y: 52 }, svgPath: 'M 32 52 L 70 52', hintText: 'うえの口の した' },
      { strokeNumber: 6, type: 'vertical', start: { x: 22, y: 58 }, end: { x: 22, y: 90 }, svgPath: 'M 22 58 L 22 90', hintText: 'そとがわの ひだりたて' },
      { strokeNumber: 7, type: 'hook', start: { x: 24, y: 60 }, end: { x: 78, y: 90 }, svgPath: 'M 24 60 L 78 60 L 78 90 L 72 90', hintText: 'そとがわの まがり' },
      { strokeNumber: 8, type: 'vertical', start: { x: 36, y: 68 }, end: { x: 36, y: 84 }, svgPath: 'M 36 68 L 36 84', hintText: 'なかの口の ひだり' },
      { strokeNumber: 9, type: 'hook', start: { x: 38, y: 70 }, end: { x: 64, y: 84 }, svgPath: 'M 38 70 L 64 70 L 64 84 L 58 84', hintText: 'なかの口の みぎ' },
      { strokeNumber: 10, type: 'horizontal', start: { x: 38, y: 84 }, end: { x: 64, y: 84 }, svgPath: 'M 38 84 L 64 84', hintText: 'なかの口の した' },
    ],
  },
];

// 2年生の全160字リスト（一覧辞書用およびチャレンジ用）
export const ALL_GRADE_2_KANJI_CHARS = [
  '引', '羽', '雲', '園', '遠', '何', '科', '夏', '家', '歌', '画', '回', '会', '海', '界', '皆',
  '角', '楽', '活', '間', '丸', '岩', '顔', '汽', '記', '帰', '弓', '牛', '魚', '京', '強', '教',
  '近', '兄', '形', '計', '元', '言', '原', '戸', '古', '午', '後', '語', '工', '公', '広', '交',
  '光', '考', '行', '高', '黄', '合', '谷', '国', '黒', '今', '才', '細', '作', '算', '止', '市',
  '矢', '姉', '思', '紙', '寺', '自', '時', '室', '社', '弱', '首', '秋', '週', '春', '書', '少',
  '場', '色', '食', '心', '新', '親', '図', '数', '西', '声', '星', '晴', '切', '雪', '船', '線',
  '前', '組', '走', '多', '太', '体', '台', '地', '池', '知', '茶', '昼', '長', '鳥', '朝', '直',
  '通', '弟', '店', '点', '電', '刀', '冬', '当', '東', '答', '頭', '同', '道', '読', '内', '南',
  '肉', '馬', '売', '買', '麦', '半', '番', '父', '風', '分', '聞', '米', '歩', '母', '方', '北',
  '毎', '妹', '万', '明', '鳴', '毛', '門', '夜', '野', '友', '用', '曜', '来', '里', '理', '話',
];
